import { convexQuery } from "@convex-dev/react-query";
import { useQueryClient } from "@tanstack/react-query";
import { createFileRoute } from "@tanstack/react-router";
import { api } from "@uncode/backend/convex/_generated/api";
import type {
  BarcodeDecodeResult,
  BarcodeEncodeActionResult,
  BarcodeRenderResult,
} from "@uncode/backend/convex/lib/barcodeTypes";
import { Badge, Button, cn, useKumoToastManager } from "@cloudflare/kumo";
import { useAction, useMutation } from "convex/react";
import { CheckCircle2, Copy, Upload } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";

import BarcodeResultCard from "@/components/barcode-result-card";
import { env } from "@uncode/env/web";

export const Route = createFileRoute("/workbench")({
  head: () => ({
    meta: [{ title: "Uncode | Workbench" }],
  }),
  validateSearch: (search: Record<string, unknown>) => ({
    text: typeof search.text === "string" ? search.text : undefined,
    tab: search.tab === "decode" ? ("decode" as const) : ("encode" as const),
  }),
  component: WorkbenchComponent,
});

const HISTORY_LIMIT = 8;
const RECENT_RUNS_QUERY = convexQuery(api.barcodes.listRecentRuns, {
  limit: HISTORY_LIMIT,
});

function buildBarcodeAssetUrl(format: "svg" | "png", plaintext: string) {
  const url = new URL(`/barcode/code128.${format}`, env.VITE_CONVEX_SITE_URL);
  url.searchParams.set("text", plaintext);
  url.searchParams.set("moduleWidth", format === "svg" ? "3" : "4");
  url.searchParams.set("barcodeHeight", format === "svg" ? "96" : "112");
  url.searchParams.set("quietZoneModules", "12");
  if (format === "svg") url.searchParams.set("label", "true");
  return url.toString();
}

const EXAMPLES = ["WO20070317", "ABC12345ZX", "81936910422665342067"] as const;

type BatchResult = {
  plaintext: string;
  encodedText?: string;
  status: string;
  errorMessage?: string;
};

function WorkbenchComponent() {
  const { text: initialText, tab: initialTab } = Route.useSearch();
  const queryClient = useQueryClient();
  const generateUploadUrl = useMutation(api.barcodes.generateUploadUrl);
  const encodeCode128 = useAction(api.barcodeNode.encodeCode128);
  const generateCode128Svg = useAction(api.barcodeNode.generateCode128Svg);
  const decodeCode128Image = useAction(api.barcodeNode.decodeCode128Image);
  const toasts = useKumoToastManager();

  const [activeTab, setActiveTab] = useState<string>(initialTab ?? "encode");
  const [plaintext, setPlaintext] = useState(initialText ?? "");
  const [pendingAction, setPendingAction] = useState<
    "generate" | "decode" | null
  >(null);
  const [result, setResult] = useState<
    | BarcodeEncodeActionResult
    | BarcodeRenderResult
    | BarcodeDecodeResult
    | null
  >(null);
  const [batchResults, setBatchResults] = useState<BatchResult[]>([]);
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [decodePreviewUrl, setDecodePreviewUrl] = useState<string>();
  const hasAutoGenerated = useRef(false);

  useEffect(() => {
    if (initialText && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      handleGenerate();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (!selectedFile) {
      setDecodePreviewUrl(undefined);
      return;
    }
    const objectUrl = URL.createObjectURL(selectedFile);
    setDecodePreviewUrl(objectUrl);
    return () => URL.revokeObjectURL(objectUrl);
  }, [selectedFile]);

  const svgDownloadUrl = useMemo(() => {
    if (result?.kind === "render" && result.svg && result.imageUrl)
      return result.imageUrl;
    return result?.plaintext
      ? buildBarcodeAssetUrl("svg", result.plaintext)
      : undefined;
  }, [result]);

  const pngDownloadUrl = useMemo(() => {
    return result?.plaintext
      ? buildBarcodeAssetUrl("png", result.plaintext)
      : undefined;
  }, [result?.plaintext]);

  async function refreshHistory() {
    await queryClient.invalidateQueries({
      queryKey: RECENT_RUNS_QUERY.queryKey,
    });
  }

  async function handleGenerate() {
    const lines = plaintext
      .split("\n")
      .map((l) => l.trim())
      .filter(Boolean);
    if (lines.length === 0) {
      toasts.add({ title: "Enter text first.", variant: "error" });
      return;
    }

    if (lines.length === 1) {
      await handleSingleGenerate(lines[0]);
    } else {
      await handleBatchGenerate(lines);
    }
  }

  async function handleSingleGenerate(text: string) {
    setPendingAction("generate");
    setBatchResults([]);
    try {
      const r = await generateCode128Svg({
        plaintext: text,
        options: {
          moduleWidth: 3,
          barcodeHeight: 96,
          quietZoneModules: 12,
          labelText: text,
          labelGap: 12,
          labelFontSize: 15,
          foreground: "#111111",
          background: "#ffffff",
        },
      });
      setResult(r);
      await refreshHistory();
      toasts.add({
        title:
          r.status === "success"
            ? "Barcode generated."
            : (r.errorMessage ?? "Failed."),
        variant: r.status === "success" ? "success" : "error",
      });
    } catch (error) {
      toasts.add({
        title:
          error instanceof Error ? error.message : "Generation failed.",
        variant: "error",
      });
    } finally {
      setPendingAction(null);
    }
  }

  async function handleBatchGenerate(lines: string[]) {
    setPendingAction("generate");
    setResult(null);
    setBatchResults([]);
    const results: BatchResult[] = [];

    for (const line of lines) {
      try {
        const r = await encodeCode128({ plaintext: line });
        results.push({
          plaintext: line,
          encodedText: r.encodedText,
          status: r.status,
          errorMessage: r.errorMessage,
        });
      } catch (error) {
        results.push({
          plaintext: line,
          status: "validation_error",
          errorMessage:
            error instanceof Error ? error.message : "Encoding failed",
        });
      }
    }

    setBatchResults(results);
    await refreshHistory();
    const successCount = results.filter((r) => r.status === "success").length;
    toasts.add({
      title: `Encoded ${successCount}/${results.length} items.`,
      variant: successCount === results.length ? "success" : "error",
    });
    setPendingAction(null);
  }

  async function handleDecode() {
    if (!selectedFile) {
      toasts.add({ title: "Choose an image first.", variant: "error" });
      return;
    }
    setPendingAction("decode");
    try {
      const uploadUrl = await generateUploadUrl({});
      const uploadResponse = await fetch(uploadUrl, {
        method: "POST",
        headers: {
          "Content-Type": selectedFile.type || "application/octet-stream",
        },
        body: selectedFile,
      });
      if (!uploadResponse.ok) throw new Error("Upload failed.");
      const uploadResult = (await uploadResponse.json()) as {
        storageId?: string;
      };
      if (!uploadResult.storageId) throw new Error("No storage ID returned.");

      const r = await decodeCode128Image({
        storageId: uploadResult.storageId as never,
      });
      setResult(r);
      await refreshHistory();
      if (r.status === "success" && r.plaintext) setPlaintext(r.plaintext);
      toasts.add({
        title:
          r.status === "success"
            ? "Decoded successfully."
            : (r.errorMessage ?? "Decode failed."),
        variant: r.status === "success" ? "success" : "error",
      });
    } catch (error) {
      toasts.add({
        title: error instanceof Error ? error.message : "Decode failed.",
        variant: "error",
      });
    } finally {
      setPendingAction(null);
    }
  }

  const encodeResult =
    result && result.kind !== "decode" ? result : null;
  const decodeResult =
    result && result.kind === "decode" ? result : null;

  const lineCount = plaintext.split("\n").length;
  const textareaRows = Math.max(1, Math.min(lineCount, 8));

  return (
    <main className="min-h-0 overflow-y-auto">
      <div className="mx-auto w-full max-w-3xl space-y-6 px-6 py-8">
        {/* Custom tabs */}
        <div className="flex gap-1 rounded-lg bg-kumo-recessed p-1">
          <button
            type="button"
            onClick={() => setActiveTab("encode")}
            className={cn(
              "flex-1 rounded-md px-4 py-2 text-sm font-medium transition-colors",
              activeTab === "encode"
                ? "bg-kumo-brand text-kumo-inverse shadow-sm"
                : "text-kumo-subtle hover:text-kumo-default",
            )}
          >
            Encode
          </button>
          <button
            type="button"
            onClick={() => setActiveTab("decode")}
            className={cn(
              "flex-1 rounded-md px-4 py-2 text-sm font-medium transition-colors",
              activeTab === "decode"
                ? "bg-kumo-brand text-kumo-inverse shadow-sm"
                : "text-kumo-subtle hover:text-kumo-default",
            )}
          >
            Decode
          </button>
        </div>

        {activeTab === "encode" ? (
          <div className="space-y-6">
            <form
              onSubmit={(e) => {
                e.preventDefault();
                handleGenerate();
              }}
              className="space-y-3"
            >
              <div className="flex gap-3">
                <textarea
                  value={plaintext}
                  onChange={(e) => setPlaintext(e.target.value)}
                  placeholder="Enter text to encode — one per line for batch"
                  autoComplete="off"
                  spellCheck={false}
                  rows={textareaRows}
                  className="flex-1 resize-y rounded-lg border border-kumo-line bg-kumo-elevated px-4 py-2.5 text-sm text-kumo-default placeholder:text-kumo-subtle transition-colors focus:border-kumo-default/30 focus:outline-none"
                />
                <div className="flex items-end">
                  <Button
                    type="submit"
                    variant="primary"
                    size="sm"
                    disabled={!plaintext.trim() || pendingAction !== null}
                  >
                    {pendingAction === "generate"
                      ? "Generating..."
                      : "Generate"}
                  </Button>
                </div>
              </div>

              <div className="flex flex-wrap gap-1.5">
                {EXAMPLES.map((example) => (
                  <button
                    key={example}
                    type="button"
                    onClick={() => setPlaintext(example)}
                    className="rounded-md bg-kumo-recessed px-2.5 py-1 font-mono text-xs text-kumo-subtle transition-colors hover:bg-kumo-tint hover:text-kumo-default"
                  >
                    {example}
                  </button>
                ))}
              </div>
            </form>

            {batchResults.length > 0 ? (
              <BatchResultsView results={batchResults} />
            ) : encodeResult ? (
              <BarcodeResultCard
                result={encodeResult}
                svgDownloadUrl={svgDownloadUrl}
                pngDownloadUrl={pngDownloadUrl}
              />
            ) : null}
          </div>
        ) : (
          <div className="space-y-6">
            <div className="space-y-4">
              {decodePreviewUrl ? (
                <div className="overflow-hidden rounded-lg bg-white">
                  <img
                    src={decodePreviewUrl}
                    alt="Uploaded barcode"
                    className="h-40 w-full object-contain p-4"
                  />
                </div>
              ) : (
                <label
                  htmlFor="decode-upload"
                  className="flex cursor-pointer flex-col items-center justify-center rounded-lg border border-dashed border-kumo-line bg-kumo-elevated px-4 py-12 text-center transition-colors hover:border-kumo-default/30 hover:bg-kumo-tint"
                >
                  <Upload className="size-6 text-kumo-subtle" />
                  <p className="mt-3 text-sm font-medium text-kumo-default">
                    Upload barcode image
                  </p>
                  <p className="mt-1 text-xs text-kumo-subtle">PNG or JPEG</p>
                  <input
                    id="decode-upload"
                    type="file"
                    accept="image/png,image/jpeg"
                    onChange={(e) =>
                      setSelectedFile(e.target.files?.[0] ?? null)
                    }
                    className="sr-only"
                  />
                </label>
              )}

              {decodePreviewUrl && (
                <div className="flex items-center justify-between">
                  <p className="font-mono text-xs text-kumo-subtle">
                    {selectedFile?.name}
                  </p>
                  <label
                    htmlFor="decode-replace"
                    className="cursor-pointer text-xs text-kumo-link hover:underline"
                  >
                    Choose different image
                    <input
                      id="decode-replace"
                      type="file"
                      accept="image/png,image/jpeg"
                      onChange={(e) =>
                        setSelectedFile(e.target.files?.[0] ?? null)
                      }
                      className="sr-only"
                    />
                  </label>
                </div>
              )}

              <Button
                type="button"
                variant="primary"
                onClick={handleDecode}
                disabled={!selectedFile || pendingAction === "decode"}
                className="w-full"
              >
                {pendingAction === "decode"
                  ? "Decoding..."
                  : "Upload and decode"}
              </Button>
            </div>

            {decodeResult && (
              <BarcodeResultCard
                result={decodeResult}
                svgDownloadUrl={svgDownloadUrl}
                pngDownloadUrl={pngDownloadUrl}
                imagePreviewUrl={
                  result?.kind === "decode"
                    ? (result.imageUrl ?? decodePreviewUrl)
                    : undefined
                }
              />
            )}
          </div>
        )}
      </div>
    </main>
  );
}

function BatchResultsView({ results }: { results: BatchResult[] }) {
  const [copiedAll, setCopiedAll] = useState(false);
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);

  const successResults = results.filter(
    (r) => r.status === "success" && r.encodedText,
  );

  async function handleCopyAll() {
    const text = successResults.map((r) => r.encodedText).join("\n");
    await navigator.clipboard.writeText(text);
    setCopiedAll(true);
    setTimeout(() => setCopiedAll(false), 1800);
  }

  async function handleCopySingle(index: number, text: string) {
    await navigator.clipboard.writeText(text);
    setCopiedIndex(index);
    setTimeout(() => setCopiedIndex(null), 1800);
  }

  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between">
        <p className="text-sm text-kumo-subtle">
          {successResults.length}/{results.length} encoded
        </p>
        {successResults.length > 0 && (
          <button
            type="button"
            onClick={handleCopyAll}
            className={cn(
              "flex items-center gap-1.5 rounded-md px-3 py-1.5 text-xs font-medium transition-colors",
              copiedAll
                ? "text-kumo-success"
                : "bg-kumo-recessed text-kumo-subtle hover:text-kumo-default",
            )}
          >
            {copiedAll ? (
              <>
                <CheckCircle2 className="size-3.5" />
                Copied
              </>
            ) : (
              <>
                <Copy className="size-3.5" />
                Copy all encoded texts
              </>
            )}
          </button>
        )}
      </div>

      <div className="divide-y divide-kumo-line rounded-lg border border-kumo-line bg-kumo-elevated">
        {results.map((r, i) => (
          <div key={i} className="flex items-center gap-3 px-4 py-3">
            <div className="min-w-0 flex-1">
              <div className="flex items-center gap-2">
                <p className="truncate font-mono text-sm">{r.plaintext}</p>
                <Badge
                  variant={
                    r.status === "success" ? "success" : "destructive"
                  }
                >
                  {r.status === "success" ? "OK" : "Failed"}
                </Badge>
              </div>
              {r.encodedText && (
                <p className="mt-1 truncate font-mono text-xs text-kumo-subtle">
                  {r.encodedText}
                </p>
              )}
              {r.status !== "success" && r.errorMessage && (
                <p className="mt-1 truncate text-xs text-kumo-danger">
                  {r.errorMessage}
                </p>
              )}
            </div>
            {r.encodedText && (
              <button
                type="button"
                onClick={() => handleCopySingle(i, r.encodedText!)}
                className="shrink-0 rounded-md p-1.5 text-kumo-subtle transition-colors hover:bg-kumo-tint hover:text-kumo-default"
              >
                {copiedIndex === i ? (
                  <CheckCircle2 className="size-4 text-kumo-success" />
                ) : (
                  <Copy className="size-4" />
                )}
              </button>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
