import { convexQuery } from "@convex-dev/react-query";
import { useQueryClient } from "@tanstack/react-query";
import { createFileRoute } from "@tanstack/react-router";
import { api } from "@uncode/backend/convex/_generated/api";
import type {
  BarcodeDecodeResult,
  BarcodeEncodeActionResult,
  BarcodeRenderResult,
  BarcodeSymbology,
} from "@uncode/backend/convex/lib/barcodeTypes";
import type { BarcodeTypeClientDefinition } from "@uncode/backend/convex/barcode/types";
import { Badge, Button, buttonVariants, cn, useKumoToastManager } from "@cloudflare/kumo";
import { useAction, useMutation, useQuery } from "convex/react";
import { ArrowRight, CheckCircle2, Copy, Download, Loader2, Upload } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";

import BarcodeResultCard from "@/components/barcode-result-card";
import { addSessionRun } from "@/lib/session-run-store";
import { env } from "@uncode/env/web";

export const Route = createFileRoute("/workbench")({
  ssr: false,
  head: () => ({
    meta: [{ title: "Uncode | Workbench" }],
  }),
  validateSearch: (search: Record<string, unknown>) => ({
    text: typeof search.text === "string" ? search.text : undefined,
    tab: search.tab === "decode" ? ("decode" as const) : ("encode" as const),
  }),
  component: WorkbenchComponent,
});

const HISTORY_LIMIT = 8;
const RECENT_RUNS_QUERY = convexQuery(api.barcodes.listRecentRuns, {
  limit: HISTORY_LIMIT,
});

function getDefaultRenderOptions(
  format: "svg" | "png",
  plaintext: string,
  symbology = "code128",
): Record<string, string | number | boolean> {
  if (symbology === "qr") {
    return {
      size: 275,
      qz: 2,
      correction: "M",
      foreground: "#111111",
      background: "#ffffff",
    };
  }

  if (symbology === "ean13" || symbology === "ean8" || symbology === "upca") {
    return {
      moduleWidth: format === "svg" ? 3 : 4,
      barcodeHeight: format === "svg" ? 96 : 112,
      quietZoneModules: 12,
      foreground: "#111111",
      background: "#ffffff",
    };
  }

  return {
    moduleWidth: format === "svg" ? 3 : 4,
    barcodeHeight: format === "svg" ? 96 : 112,
    quietZoneModules: 12,
    ...(format === "svg"
      ? {
          labelText: plaintext,
          labelGap: 12,
          labelFontSize: 15,
          foreground: "#111111",
          background: "#ffffff",
        }
      : {
          foreground: "#111111",
          background: "#ffffff",
        }),
  };
}

function buildBarcodeAssetUrl(args: {
  format: "svg" | "png";
  symbology: string;
  plaintext: string;
  options?: Record<string, string | number | boolean>;
}) {
  const url = new URL(`/barcode/render.${args.format}`, env.VITE_CONVEX_SITE_URL);
  url.searchParams.set("type", args.symbology);
  url.searchParams.set("text", args.plaintext);
  for (const [key, value] of Object.entries(args.options ?? {})) {
    url.searchParams.set(key, String(value));
  }
  return url.toString();
}

type BatchResult = {
  plaintext: string;
  encodedText?: string;
  status: string;
  symbology: string;
  errorMessage?: string;
};

function WorkbenchComponent() {
  const { text: initialText, tab: activeTab } = Route.useSearch();
  const navigate = Route.useNavigate();
  const queryClient = useQueryClient();
  const currentUser = useQuery(api.auth.getCurrentUser);
  const barcodeTypes = useQuery(api.barcodeTypes.list);
  const isAnonymous = !currentUser || currentUser.isAnonymous;
  const generateUploadUrl = useMutation(api.barcodes.generateUploadUrl);
  const batchEncodeBarcodes = useAction(api.barcode.batch.batchEncodeBarcodes);
  const generateBarcodeSvg = useAction(api.barcodeActions.generateBarcodeSvg);
  const decodeBarcodeImage = useAction(api.barcodeNode.decodeBarcodeImage);
  const createShare = useMutation(api.barcode.shares.createShare);
  const toasts = useKumoToastManager();

  const [plaintext, setPlaintext] = useState(initialText ?? "");
  const [selectedSymbology, setSelectedSymbology] = useState<BarcodeSymbology>("code128");
  const [renderOptions, setRenderOptions] = useState<Record<string, string | number | boolean>>({});
  const [pendingAction, setPendingAction] = useState<"generate" | "decode" | null>(null);
  const [result, setResult] = useState<
    BarcodeEncodeActionResult | BarcodeRenderResult | BarcodeDecodeResult | null
  >(null);
  const [batchResults, setBatchResults] = useState<BatchResult[]>([]);
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [decodePreviewUrl, setDecodePreviewUrl] = useState<string>();
  const hasAutoGenerated = useRef(false);

  useEffect(() => {
    if (initialText && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      handleGenerate();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (!selectedFile) {
      setDecodePreviewUrl(undefined);
      return;
    }
    const objectUrl = URL.createObjectURL(selectedFile);
    setDecodePreviewUrl(objectUrl);
    return () => URL.revokeObjectURL(objectUrl);
  }, [selectedFile]);

  const selectedBarcodeType = barcodeTypes?.find((type) => type.symbology === selectedSymbology);

  useEffect(() => {
    if (!selectedBarcodeType) return;
    const defaults = Object.fromEntries(
      Object.entries(selectedBarcodeType.options).map(([key, option]) => [key, option.default]),
    );
    setRenderOptions(defaults);
  }, [selectedBarcodeType]);

  const svgDownloadUrl = useMemo(() => {
    if (result?.kind === "render" && result.svg && result.imageUrl) return result.imageUrl;
    return result?.plaintext
      ? buildBarcodeAssetUrl({
          format: "svg",
          symbology: result.symbology,
          plaintext: result.plaintext,
          options: renderOptions,
        })
      : undefined;
  }, [result]);

  const pngDownloadUrl = useMemo(() => {
    return result?.plaintext
      ? buildBarcodeAssetUrl({
          format: "png",
          symbology: result.symbology,
          plaintext: result.plaintext,
          options: renderOptions,
        })
      : undefined;
  }, [result]);

  async function refreshHistory() {
    await queryClient.invalidateQueries({
      queryKey: RECENT_RUNS_QUERY.queryKey,
    });
  }

  async function handleShareCurrent() {
    const item = result?.plaintext
      ? { symbology: result.symbology, plaintext: result.plaintext }
      : batchResults.find((batchResult) => batchResult.status === "success");
    if (!item) return;
    const share = await createShare({
      items: [
        {
          symbology: item.symbology as BarcodeSymbology,
          plaintext: item.plaintext,
          outputFormat: "svg",
          options: renderOptions,
        },
      ],
    });
    const url = `${window.location.origin}/share/${share.shareKey}`;
    await navigator.clipboard.writeText(url);
    toasts.add({ title: "Share link copied.", variant: "success" });
  }

  async function handleGenerate() {
    const lines = plaintext
      .split("\n")
      .map((l) => l.trim())
      .filter(Boolean);
    if (lines.length === 0) {
      toasts.add({ title: "Enter text first.", variant: "error" });
      return;
    }

    if (lines.length === 1) {
      await handleSingleGenerate(lines[0]);
    } else {
      await handleBatchGenerate(lines);
    }
  }

  async function handleSingleGenerate(text: string) {
    setPendingAction("generate");
    setBatchResults([]);
    try {
      const r = await generateBarcodeSvg({
        symbology: selectedSymbology,
        plaintext: text,
        options: {
          ...renderOptions,
          labelText: renderOptions.labelText === true ? text : renderOptions.labelText,
        },
      });
      setResult(r);
      if (isAnonymous) {
        addSessionRun({
          kind: r.kind,
          status: r.status,
          symbology: r.symbology,
          plaintext: r.plaintext,
          errorMessage: r.errorMessage,
        });
      } else {
        await refreshHistory();
      }
      toasts.add({
        title: r.status === "success" ? "Barcode generated." : (r.errorMessage ?? "Failed."),
        variant: r.status === "success" ? "success" : "error",
      });
    } catch (error) {
      toasts.add({
        title: error instanceof Error ? error.message : "Generation failed.",
        variant: "error",
      });
    } finally {
      setPendingAction(null);
    }
  }

  async function handleBatchGenerate(lines: string[]) {
    setPendingAction("generate");
    setResult(null);
    setBatchResults([]);
    const results = await batchEncodeBarcodes({
      items: lines.map((line) => ({
        plaintext: line,
        symbology: selectedSymbology,
        options: renderOptions,
      })),
    });

    setBatchResults(results);
    if (isAnonymous) {
      for (const r of results) {
        addSessionRun({
          kind: "encode",
          status: r.status,
          symbology: r.symbology,
          plaintext: r.plaintext,
          errorMessage: r.errorMessage,
        });
      }
    } else {
      await refreshHistory();
    }
    const successCount = results.filter((r) => r.status === "success").length;
    toasts.add({
      title: `Encoded ${successCount}/${results.length} items.`,
      variant: successCount === results.length ? "success" : "error",
    });
    setPendingAction(null);
  }

  async function handleDecode() {
    if (!selectedFile) {
      toasts.add({ title: "Choose an image first.", variant: "error" });
      return;
    }
    setPendingAction("decode");
    try {
      const uploadUrl = await generateUploadUrl({});
      const uploadResponse = await fetch(uploadUrl, {
        method: "POST",
        headers: {
          "Content-Type": selectedFile.type || "application/octet-stream",
        },
        body: selectedFile,
      });
      if (!uploadResponse.ok) throw new Error("Upload failed.");
      const uploadResult = (await uploadResponse.json()) as {
        storageId?: string;
      };
      if (!uploadResult.storageId) throw new Error("No storage ID returned.");

      const r = await decodeBarcodeImage({
        storageId: uploadResult.storageId as never,
        symbology: selectedSymbology,
      });
      setResult(r);
      if (isAnonymous) {
        addSessionRun({
          kind: r.kind,
          status: r.status,
          symbology: r.symbology,
          plaintext: r.plaintext,
          errorMessage: r.errorMessage,
        });
      } else {
        await refreshHistory();
      }
      if (r.status === "success" && r.plaintext) setPlaintext(r.plaintext);
      toasts.add({
        title:
          r.status === "success" ? "Decoded successfully." : (r.errorMessage ?? "Decode failed."),
        variant: r.status === "success" ? "success" : "error",
      });
    } catch (error) {
      toasts.add({
        title: error instanceof Error ? error.message : "Decode failed.",
        variant: "error",
      });
    } finally {
      setPendingAction(null);
    }
  }

  const encodeResult = result && result.kind !== "decode" ? result : null;
  const decodeResult = result && result.kind === "decode" ? result : null;

  const lineCount = plaintext.split("\n").length;
  const textareaRows = Math.max(1, Math.min(lineCount, 8));

  return (
    <main className="min-h-0 overflow-y-auto">
      <div className="mx-auto w-full max-w-3xl space-y-6 px-6 py-8">
        {/* Custom tabs */}
        <div className="flex gap-1 rounded-lg bg-kumo-recessed p-1">
          <button
            type="button"
            onClick={() => navigate({ search: (prev) => ({ ...prev, tab: "encode" }) })}
            className={cn(
              "flex-1 rounded-md px-4 py-2 text-sm font-medium transition-colors",
              activeTab === "encode"
                ? "bg-kumo-brand text-white shadow-sm"
                : "text-kumo-subtle hover:text-kumo-default",
            )}
          >
            Encode
          </button>
          <button
            type="button"
            onClick={() => navigate({ search: (prev) => ({ ...prev, tab: "decode" }) })}
            className={cn(
              "flex-1 rounded-md px-4 py-2 text-sm font-medium transition-colors",
              activeTab === "decode"
                ? "bg-kumo-brand text-white shadow-sm"
                : "text-kumo-subtle hover:text-kumo-default",
            )}
          >
            Decode
          </button>
        </div>

        {activeTab === "encode" ? (
          <div className="space-y-6">
            <form
              onSubmit={(e) => {
                e.preventDefault();
                handleGenerate();
              }}
              className="space-y-3"
            >
              <div className="grid gap-3 sm:grid-cols-[12rem_1fr_auto]">
                <select
                  value={selectedSymbology}
                  onChange={(e) => setSelectedSymbology(e.target.value as BarcodeSymbology)}
                  className="h-12 rounded-xl border border-kumo-line bg-kumo-elevated px-4 text-sm text-kumo-default focus:border-kumo-default/30 focus:outline-none"
                >
                  {(barcodeTypes ?? []).map((type) => (
                    <option key={type.symbology} value={type.symbology}>
                      {type.displayName}
                    </option>
                  ))}
                </select>
                <textarea
                  value={plaintext}
                  onChange={(e) => setPlaintext(e.target.value)}
                  placeholder="Enter text to encode — one per line for batch"
                  autoComplete="off"
                  spellCheck={false}
                  rows={textareaRows}
                  className="min-h-12 resize-y rounded-xl border border-kumo-line bg-kumo-elevated px-5 py-3 text-[15px] text-kumo-default placeholder:text-kumo-subtle transition-colors focus:border-kumo-default/30 focus:outline-none"
                />
                <button
                  type="submit"
                  disabled={!plaintext.trim() || pendingAction !== null}
                  className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-kumo-brand text-white transition-colors hover:bg-kumo-brand-hover disabled:cursor-not-allowed disabled:opacity-40"
                >
                  {pendingAction === "generate" ? (
                    <Loader2 className="size-5 animate-spin" />
                  ) : (
                    <ArrowRight className="size-5" />
                  )}
                </button>
              </div>

              {selectedBarcodeType && (
                <BarcodeOptionsPanel
                  type={selectedBarcodeType}
                  options={renderOptions}
                  onChange={setRenderOptions}
                />
              )}

              {barcodeTypes?.find((type) => type.symbology === selectedSymbology)?.examples
                .length ? (
                <p className="text-xs text-kumo-subtle">
                  Example:{" "}
                  {barcodeTypes.find((type) => type.symbology === selectedSymbology)?.examples[0]}
                </p>
              ) : null}
            </form>

            {batchResults.length > 0 ? (
              <>
                <BatchResultsView results={batchResults} />
                <Button type="button" variant="secondary" onClick={handleShareCurrent}>
                  Share first result
                </Button>
              </>
            ) : encodeResult ? (
              <div className="space-y-3">
                <BarcodeResultCard
                  result={encodeResult}
                  svgDownloadUrl={svgDownloadUrl}
                  pngDownloadUrl={pngDownloadUrl}
                />
                <Button type="button" variant="secondary" onClick={handleShareCurrent}>
                  Share
                </Button>
              </div>
            ) : null}
          </div>
        ) : (
          <div className="space-y-6">
            <div className="space-y-4">
              <select
                value={selectedSymbology}
                onChange={(e) => setSelectedSymbology(e.target.value as BarcodeSymbology)}
                className="h-12 w-full rounded-xl border border-kumo-line bg-kumo-elevated px-4 text-sm text-kumo-default focus:border-kumo-default/30 focus:outline-none"
              >
                {(barcodeTypes ?? []).map((type) => (
                  <option key={type.symbology} value={type.symbology}>
                    Decode as {type.displayName}
                  </option>
                ))}
              </select>
              {decodePreviewUrl ? (
                <div className="overflow-hidden rounded-lg bg-white">
                  <img
                    src={decodePreviewUrl}
                    alt="Uploaded barcode"
                    className="h-40 w-full object-contain p-4"
                  />
                </div>
              ) : (
                <label
                  htmlFor="decode-upload"
                  className="flex cursor-pointer flex-col items-center justify-center rounded-lg border border-dashed border-kumo-line bg-kumo-elevated px-4 py-12 text-center transition-colors hover:border-kumo-default/30 hover:bg-kumo-tint"
                >
                  <Upload className="size-6 text-kumo-subtle" />
                  <p className="mt-3 text-sm font-medium text-kumo-default">Upload barcode image</p>
                  <p className="mt-1 text-xs text-kumo-subtle">PNG or JPEG</p>
                  <input
                    id="decode-upload"
                    type="file"
                    accept="image/png,image/jpeg"
                    onChange={(e) => setSelectedFile(e.target.files?.[0] ?? null)}
                    className="sr-only"
                  />
                </label>
              )}

              {decodePreviewUrl && (
                <div className="flex items-center justify-between">
                  <p className="font-mono text-xs text-kumo-subtle">{selectedFile?.name}</p>
                  <label
                    htmlFor="decode-replace"
                    className="cursor-pointer text-xs text-kumo-link hover:underline"
                  >
                    Choose different image
                    <input
                      id="decode-replace"
                      type="file"
                      accept="image/png,image/jpeg"
                      onChange={(e) => setSelectedFile(e.target.files?.[0] ?? null)}
                      className="sr-only"
                    />
                  </label>
                </div>
              )}

              <Button
                type="button"
                variant="primary"
                onClick={handleDecode}
                disabled={!selectedFile || pendingAction === "decode"}
              >
                {pendingAction === "decode" ? (
                  <>
                    Decoding…
                    <Loader2 className="size-4 animate-spin" />
                  </>
                ) : (
                  <>
                    Upload and decode
                    <ArrowRight className="size-4" />
                  </>
                )}
              </Button>
            </div>

            {decodeResult && (
              <BarcodeResultCard
                result={decodeResult}
                svgDownloadUrl={svgDownloadUrl}
                pngDownloadUrl={pngDownloadUrl}
                imagePreviewUrl={
                  result?.kind === "decode" ? (result.imageUrl ?? decodePreviewUrl) : undefined
                }
              />
            )}
          </div>
        )}
      </div>
    </main>
  );
}

function BarcodeOptionsPanel({
  type,
  options,
  onChange,
}: {
  type: BarcodeTypeClientDefinition;
  options: Record<string, string | number | boolean>;
  onChange: (options: Record<string, string | number | boolean>) => void;
}) {
  const visibleOptions = Object.entries(type.options).filter(
    ([key]) => !["labelGap", "labelFontSize", "labelFontFamily"].includes(key),
  );
  if (visibleOptions.length === 0) return null;
  return (
    <div className="grid gap-x-4 gap-y-3 rounded-xl border border-kumo-line bg-kumo-elevated px-4 py-4 sm:grid-cols-2 lg:grid-cols-4">
      {visibleOptions.map(([key, option]) => (
        <label key={key} className="flex flex-col gap-1.5 text-xs text-kumo-subtle">
          <span className="font-medium">{option.label}</span>
          {option.kind === "enum" ? (
            <select
              value={String(options[key] ?? option.default)}
              onChange={(e) => onChange({ ...options, [key]: e.target.value })}
              className="h-9 w-full rounded-md border border-kumo-line bg-kumo-recessed px-2 text-sm text-kumo-default focus:border-kumo-default/30 focus:outline-none"
            >
              {option.values.map((value) => (
                <option key={value} value={value}>
                  {value}
                </option>
              ))}
            </select>
          ) : option.kind === "boolean" ? (
            <input
              type="checkbox"
              checked={Boolean(options[key] ?? option.default)}
              onChange={(e) => onChange({ ...options, [key]: e.target.checked })}
              className="size-5"
            />
          ) : option.kind === "color" ? (
            <input
              type="color"
              value={String(options[key] ?? option.default)}
              onChange={(e) => onChange({ ...options, [key]: e.target.value })}
              className="h-9 w-full cursor-pointer rounded-md border border-kumo-line bg-kumo-recessed p-1"
            />
          ) : (
            <input
              type={option.kind === "number" ? "number" : "text"}
              value={String(options[key] ?? option.default)}
              min={option.kind === "number" ? option.min : undefined}
              max={option.kind === "number" ? option.max : undefined}
              onChange={(e) =>
                onChange({
                  ...options,
                  [key]: option.kind === "number" ? Number(e.target.value) : e.target.value,
                })
              }
              className="h-9 w-full rounded-md border border-kumo-line bg-kumo-recessed px-2 text-sm text-kumo-default focus:border-kumo-default/30 focus:outline-none"
            />
          )}
        </label>
      ))}
    </div>
  );
}

function BatchResultsView({ results }: { results: BatchResult[] }) {
  const [copiedAll, setCopiedAll] = useState(false);
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);

  const successResults = results.filter((r) => r.status === "success" && r.encodedText);

  async function handleCopyAll() {
    const text = successResults.map((r) => r.encodedText).join("\n");
    await navigator.clipboard.writeText(text);
    setCopiedAll(true);
    setTimeout(() => setCopiedAll(false), 1800);
  }

  async function handleCopySingle(index: number, text: string) {
    await navigator.clipboard.writeText(text);
    setCopiedIndex(index);
    setTimeout(() => setCopiedIndex(null), 1800);
  }

  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between">
        <p className="text-sm text-kumo-subtle">
          {successResults.length}/{results.length} encoded
        </p>
        {successResults.length > 0 && (
          <button
            type="button"
            onClick={handleCopyAll}
            className={cn(
              "flex items-center gap-1.5 rounded-md px-3 py-1.5 text-xs font-medium transition-colors",
              copiedAll
                ? "text-kumo-success"
                : "bg-kumo-recessed text-kumo-subtle hover:text-kumo-default",
            )}
          >
            {copiedAll ? (
              <>
                <CheckCircle2 className="size-3.5" />
                Copied
              </>
            ) : (
              <>
                <Copy className="size-3.5" />
                Copy all encoded texts
              </>
            )}
          </button>
        )}
      </div>

      <div className="divide-y divide-kumo-line rounded-lg border border-kumo-line bg-kumo-elevated">
        {results.map((r, i) => (
          <div key={i} className="flex items-center gap-3 px-4 py-3">
            <div className="min-w-0 flex-1">
              <p className="truncate font-mono text-sm">{r.plaintext}</p>
              {r.encodedText && (
                <p className="mt-1 truncate font-mono text-xs text-kumo-subtle">{r.encodedText}</p>
              )}
              {r.status !== "success" && (
                <p className="mt-1 truncate text-xs text-kumo-danger">
                  <Badge variant="destructive" className="mr-1.5">
                    Failed
                  </Badge>
                  {r.errorMessage}
                </p>
              )}
            </div>
            <div className="flex shrink-0 items-center gap-1.5">
              {r.plaintext && r.status === "success" && (
                <>
                  <a
                    href={buildBarcodeAssetUrl({
                      format: "svg",
                      symbology: r.symbology,
                      plaintext: r.plaintext,
                      options: getDefaultRenderOptions("svg", r.plaintext, r.symbology),
                    })}
                    target="_blank"
                    rel="noreferrer"
                    className={cn(
                      buttonVariants({ variant: "ghost", size: "sm" }),
                      "h-auto px-1.5 py-1 text-xs",
                    )}
                  >
                    <Download className="size-3" />
                    SVG
                  </a>
                  <a
                    href={buildBarcodeAssetUrl({
                      format: "png",
                      symbology: r.symbology,
                      plaintext: r.plaintext,
                      options: getDefaultRenderOptions("png", r.plaintext, r.symbology),
                    })}
                    target="_blank"
                    rel="noreferrer"
                    className={cn(
                      buttonVariants({ variant: "ghost", size: "sm" }),
                      "h-auto px-1.5 py-1 text-xs",
                    )}
                  >
                    <Download className="size-3" />
                    PNG
                  </a>
                </>
              )}
              {r.encodedText && (
                <button
                  type="button"
                  onClick={() => handleCopySingle(i, r.encodedText!)}
                  className="rounded-md p-1.5 text-kumo-subtle transition-colors hover:bg-kumo-tint hover:text-kumo-default"
                >
                  {copiedIndex === i ? (
                    <CheckCircle2 className="size-4 text-kumo-success" />
                  ) : (
                    <Copy className="size-4" />
                  )}
                </button>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
